Feature/boas 1122 prod url
Planning-Inspectorate/infrastructure-environments pull request #696
Opened 2024-03-08 11:45 UTC by HadrianHughesKC

# Pull Request Template

## Describe your changes

* Add new requested prod URL and rename old URL
* Set up a redirect from the old back-office URL to the new one

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] My code changes do not include any hardcoded secrets or passwords
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My Tech Lead is aware of any infrastructure changes that will cost money

2024-03-08 15:36 UTC, beejjacobs requested changes
Couple of points, looks quite straight forward. Good work.

2024-03-08 15:36 UTC, beejjacobs commented on app/stacks/global/front-door/front-door.tf
> +  }
I think the ordering of the frontends matters (see comment on line 68). I think we move this to the end of the list.

2024-03-08 15:49 UTC, HadrianHughesKC commented on app/stacks/global/front-door/variables.tf
> +  description = "List of old URLs to be redirect to the new URL for Back Office frontend"
> Is this a list, or just a single value?

I initially intended to allow a list but then changed it, forgot to update the description. That's fixed now.

2024-03-11 12:16 UTC, beejjacobs approved these changes

2024-03-11 12:16 UTC, merged